### PR TITLE
Modify drop down style for top and sub navigation items, and minor edits to files

### PR DESCRIPTION
**Pull request by vladimir-v-diaz**
This pull request modifies the style of top and sub navigation items.

What has changed?
(1) Do not display a pointer for top navigation items that do not link to a page.
(2) Highlight top navigation items (instead of using the dotted decorator).
(3) Modify the background color of a drop down menu so that it's easier to see.
(4) Revise comments and fix typo.
(5) Delete obsolete files (`/navbar.yml` and `/adopters.md`).
(6) Mark `Implementation` link as external (indicated by arrow icon).

@JustinCappos @jhdalek55 

Do the changes look good to you?

drop_down_menu_style

Here is a screenshot that shows the pointers for a navigation item that does link to a page.

cursor_style

Signed-off-by: Vladimir Diaz \<vladimir.v.diaz@gmail.com>

### CODE REVIEW

**Comment by jhdalek55** [comment]
Will look this over as soon as I can. Dealing with a few papers today 
and tomorrow.


Lois
On Wed, May 30, 2018 at 01:57 PM, Vladimir Diaz wrote:

This pull request modifies the style of top and sub navigation items.

What has changed?

(1) Do not display a pointer for top navigation items that do not link 
to a page.

(2) Underline top navigation items (instead of using the dotted 
decorator).

(3) Modify the background color of a drop down menu so that it's easier 
to see.

@JustinCappos <https://github.com/JustinCappos>  @jhdalek55 
<https://github.com/jhdalek55>

Do the changes look good to you?

drop_down_menu_style 
<https://user-images.githubusercontent.com/3520883/40738016-67e52656-6410-11e8-8be2-e068d20afc95.png>

Here is a screenshot that shows the pointers for a navigation item that 
does link to a page.

cursor_style 
<https://user-images.githubusercontent.com/3520883/40738303-33fea028-6411-11e8-8b22-be09d602abbc.png>

Signed-off-by: Vladimir Diaz <vladimir.v.diaz@gmail.com 
<mailto:vladimir.v.diaz@gmail.com> >



You can view, comment on, or merge this pull request online at:

  https://github.com/theupdateframework/theupdateframework.github.io/pull/37 
<https://github.com/theupdateframework/theupdateframework.github.io/pull/37>

Commit Summary

    * Modify drop down style for top and sub navigation items


File Changes

    *
     M
     _sass/navbar.scss 
<https://github.com/theupdateframework/theupdateframework.github.io/pull/37/files#diff-0>
     (21)



Patch Links:

    * 
https://github.com/theupdateframework/theupdateframework.github.io/pull/37.patch 
<https://github.com/theupdateframework/theupdateframework.github.io/pull/37.patch>
    * 
https://github.com/theupdateframework/theupdateframework.github.io/pull/37.diff 
<https://github.com/theupdateframework/theupdateframework.github.io/pull/37.diff>



—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub 
<https://github.com/theupdateframework/theupdateframework.github.io/pull/37> 
, or mute the thread

**Comment by vladimir-v-diaz** [comment]
Thanks, Lois.

Note: You don't need to review the code changes, just the screenshots.  I'd like verify that the new style changes are good enough.

**Comment by vladimir-v-diaz** [comment]
@JustinCappos 
Here is a screenshot of what happens when you hover over a menu item.  Note that the text is no longer underlined, and it is highlighted.  Text is only underlined if it links to a page.

highlight_top_nav

**Comment by JustinCappos** [comment]
Great!

**Pull request merged**
